# This file was generated by the {rix} R package v0.9.1 on 2024-09-11
# with following call:
# >rix(r_ver = "6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212",
#  > r_pkgs = c("coda",
#  > "codetools",
#  > "colorspace",
#  > "cowplot",
#  > "EnvStats",
#  > "extraDistr",
#  > "ggforce",
#  > "ggplot2",
#  > "ggpubr",
#  > "MCMCvis",
#  > "paletteer",
#  > "popbio",
#  > "qs",
#  > "Rage",
#  > "reshape2",
#  > "RJSONIO",
#  > "sf",
#  > "see",
#  > "terra",
#  > "tidybayes",
#  > "tidyverse",
#  > "tmap",
#  > "viridis"),
#  > system_pkgs = c("parallel"),
#  > git_pkgs = list(list(package_name = "LivingNorwayR",
#  > repo_url = "https://github.com/LivingNorway/LivingNorwayR",
#  > commit = "ef83ae20f0be20c922a56bd4fc0053ec30d8b4a3"),
#  >      list(package_name = "nimbleDistance",
#  > repo_url = "https://github.com/scrogster/nimbleDistance",
#  > commit = "d5ea9c15dc484a7923a60a19e36f5ed5a107ca4b")),
#  > ide = "rstudio",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision 6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212 for reproducibility purposes
# which will install R version 4.4.0.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      coda
      codetools
      colorspace
      cowplot
      EnvStats
      extraDistr
      ggforce
      ggplot2
      ggpubr
      MCMCvis
      paletteer
      popbio
      qs
      Rage
      reshape2
      RJSONIO
      sf
      see
      terra
      tidybayes
      tidyverse
      tmap
      viridis;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "LivingNorwayR";
      src = pkgs.fetchgit {
        url = "https://github.com/LivingNorway/LivingNorwayR";
        rev = "ef83ae20f0be20c922a56bd4fc0053ec30d8b4a3";
        sha256 = "sha256-G6kVG+eccn5W4Mxpjefj9LYoLHb5nrNVAXpjRa3Xz2w=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          dplyr
          leaflet
          sf
          R6
          readr
          uuid
          knitr
          rmarkdown
          emld
          zip
          xml2
          here;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "nimbleDistance";
      src = pkgs.fetchgit {
        url = "https://github.com/scrogster/nimbleDistance";
        rev = "d5ea9c15dc484a7923a60a19e36f5ed5a107ca4b";
        sha256 = "sha256-WJvHASuZOuRV/QRoiDJJaUnQLx/7hSL5lc1HPCmjE3w=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          nimble;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      parallel
      R
      glibcLocales
      nix;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [ git_archive_pkgs rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";
   QT_XCB_GL_INTEGRATION = "none";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages  wrapped_pkgs ];
  
}
